url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/TemperatureDashboard" # the subpath of your site, e.g. /blog
title: "Temperature dashboard" # the name of your site, e.g. ACME Corp.
