name: Data extract

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    # Self-hosted runner with Python 3.9 and pip pre-installed
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./script/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        # Using a custom PAT with write access to the repository so it will trigger site build
        token: ${{ secrets.REPO_COMMIT_TOKEN }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env: 
        HA_TOKEN: ${{secrets.HA_TOKEN}}
      run: python ./main.py https://ha.gnet.ovh sensor.office_temperature_sensor_temperature  $HA_TOKEN
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
  